clone:
  git:
    image: plugins/git
    depth: 1

pipeline:
  check-app-compatbility:
    image: nextcloudci/php5.6:php5.6-3
    environment:
      - APP_NAME=cms_pico
      - CORE_BRANCH=master
      - DB=sqlite
    commands:
      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server

      # Code checker
      - ./occ app:check-code $APP_NAME -c strong-comparison
      - ./occ app:check-code $APP_NAME -c deprecation
      - cd apps/$APP_NAME/
    when:
      matrix:
        TESTS: check-app-compatbility
  check-app-compatbility-stable12:
    image: nextcloudci/php5.6:php5.6-3
    environment:
      - APP_NAME=cms_pico
      - CORE_BRANCH=stable12
      - DB=sqlite
    commands:
      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server

      # Code checker
      - ./occ app:check-code $APP_NAME -c strong-comparison
      - ./occ app:check-code $APP_NAME -c deprecation
      - cd apps/$APP_NAME/
    when:
      matrix:
        TESTS: check-app-compatbility-stable12
  signed-off-check:
    image: nextcloudci/php7.0:php7.0-2
    environment:
      - APP_NAME=cms_pico
      - CORE_BRANCH=master
      - DB=sqlite
    commands:
      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server
      - php ./build/signed-off-checker.php
    when:
      matrix:
        TESTS: signed-off-check
  php5.6:
    image: nextcloudci/php5.6:php5.6-3
    environment:
      - APP_NAME=cms_pico
      - CORE_BRANCH=master
      - DB=sqlite
    commands:
      - apt update && apt-get -y install php5-xdebug

      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server/apps/$APP_NAME
      - composer install
      - cd ../..
      - ./occ app:enable $APP_NAME
      - cd apps/$APP_NAME

      # Run phpunit tests
      - cd tests/
      - phpunit --configuration phpunit.xml .

      # Create coverage report
      - wget https://codecov.io/bash -O codecov.sh
      - sh -c "if [ '$DRONE_BUILD_EVENT' = 'pull_request' ]; then bash codecov.sh -B $DRONE_BRANCH -C $DRONE_COMMIT -P $DRONE_PULL_REQUEST -t 39793ffa-0439-4daa-8cab-6533f6533098 -f clover.xml; fi"
      - sh -c "if [ '$DRONE_BUILD_EVENT' != 'pull_request' ]; then bash codecov.sh -B $DRONE_BRANCH -C $DRONE_COMMIT -t 39793ffa-0439-4daa-8cab-6533f6533098 -f clover.xml; fi"
    when:
      matrix:
        TESTS: php5.6
  php7.0:
    image: nextcloudci/php7.0:php7.0-2
    environment:
      - APP_NAME=cms_pico
      - CORE_BRANCH=master
      - DB=sqlite
    commands:
      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server/apps/$APP_NAME
      - composer install
      - cd ../..
      - ./occ app:enable $APP_NAME
      - cd apps/$APP_NAME

      # Run phpunit tests
      - cd tests/
      - phpunit --configuration phpunit.xml .
    when:
      matrix:
        TESTS: php7.0
  php7.1:
    image: nextcloudci/php7.1:php7.1-12
    environment:
      - APP_NAME=cms_pico
      - CORE_BRANCH=master
      - DB=sqlite
    commands:
      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server/apps/$APP_NAME
      - composer install
      - cd ../..
      - ./occ app:enable $APP_NAME
      - cd apps/$APP_NAME

      # Run phpunit tests
      - cd tests/
      - phpunit --configuration phpunit.xml .
    when:
      matrix:
        TESTS: php7.1
  php5.6-stable12:
    image: nextcloudci/php5.6:php5.6-3
    environment:
      - APP_NAME=cms_pico
      - CORE_BRANCH=stable12
      - DB=sqlite
    commands:
      - apt update && apt-get -y install php5-xdebug

      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server/apps/$APP_NAME
      - composer install
      - cd ../..
      - ./occ app:enable $APP_NAME
      - cd apps/$APP_NAME

      # Run phpunit tests
      - cd tests/
      - phpunit --configuration phpunit.xml .

      # Create coverage report
      - wget https://codecov.io/bash -O codecov.sh
      - sh -c "if [ '$DRONE_BUILD_EVENT' = 'pull_request' ]; then bash codecov.sh -B $DRONE_BRANCH -C $DRONE_COMMIT -P $DRONE_PULL_REQUEST -t 39793ffa-0439-4daa-8cab-6533f6533098 -f clover.xml; fi"
      - sh -c "if [ '$DRONE_BUILD_EVENT' != 'pull_request' ]; then bash codecov.sh -B $DRONE_BRANCH -C $DRONE_COMMIT -t 39793ffa-0439-4daa-8cab-6533f6533098 -f clover.xml; fi"
    when:
      matrix:
        TESTS: php5.6-stable12
  php7.0-stable12:
    image: nextcloudci/php7.0:php7.0-2
    environment:
      - APP_NAME=cms_pico
      - CORE_BRANCH=stable12
      - DB=sqlite
    commands:
      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server/apps/$APP_NAME
      - composer install
      - cd ../..
      - ./occ app:enable $APP_NAME
      - cd apps/$APP_NAME

      # Run phpunit tests
      - cd tests/
      - phpunit --configuration phpunit.xml .
    when:
      matrix:
        TESTS: php7.0-stable12

  php7.1-stable12:
    image: nextcloudci/php7.1:php7.1-12
    environment:
      - APP_NAME=cms_pico
      - CORE_BRANCH=stable12
      - DB=sqlite
    commands:
      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server/apps/$APP_NAME
      - composer install
      - cd ../..
      - ./occ app:enable $APP_NAME
      - cd apps/$APP_NAME

      # Run phpunit tests
      - cd tests/
      - phpunit --configuration phpunit.xml .
    when:
      matrix:
        TESTS: php7.1-stable12

 php7.1-stable12-mysql:
    image: nextcloudci/php7.1:php7.1-12
    environment:
      - APP_NAME=cms_pico
      - CORE_BRANCH=stable12
      - DB=mysql
    commands:
      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server/apps/$APP_NAME
      - composer install
      - cd ../..
      - ./occ app:enable $APP_NAME
      - cd apps/$APP_NAME

      # Run phpunit tests
      - cd tests/
      - phpunit --configuration phpunit.xml .
    when:
      matrix:
        TESTS: php7.1-stable12


matrix:
  include:
    - TESTS: php5.6
    - TESTS: php7.0
    - TESTS: php7.1
    - TESTS: php5.6-stable12
    - TESTS: php7.0-stable12
    - TESTS: php7.1-stable12
    - TESTS: check-app-compatbility
    - TESTS: check-app-compatbility-stable12
    - TESTS: signed-off-check
