build:
  nodes:
    analysis:
      dependencies:
        after:
          - curl -L https://download.nextcloud.com/server/releases/latest.tar.bz2 | tar xj
      tests:
        override:
          - php-scrutinizer-run
          - phpcs-run --standard=.phpcs.xml
          - js-scrutinizer-run

checks:
  php: true
  javascript: true

filter:
  excluded_paths:
    - appdata/plugins/
    - appdata/themes/
    - l10n/
    - tests/
  dependency_paths:
    - vendor/
    - nextcloud/
