build:
  environment:
    php:
      pecl_extensions:
        - zip
    variables:
      APP_NAME: cms_pico
      NEXTCLOUD: releases/latest
  nodes:
    analysis:
      environment:
        php:
          version: 7.3
          pecl_extensions:
            - xdebug
      dependencies:
        override:
          - curl -L -o ~/nextcloud.tar.bz2 https://download.nextcloud.com/server/$NEXTCLOUD.tar.bz2
          - curl -L -o ~/phpunit.phar https://phar.phpunit.de/phpunit-6.phar
      project_setup:
        override:
          - make build
          - cp build/$APP_NAME-*.tar.gz ~/$APP_NAME.tar.gz

          - tar xfjv ~/nextcloud.tar.bz2

          - tar xfjv ~/nextcloud.tar.bz2 -C ~
          - tar xfzv ~/$APP_NAME.tar.gz -C ~/nextcloud/apps
          - cp -rv tests ~/nextcloud/apps/$APP_NAME/tests

          - cd ~/nextcloud
          - php ./occ --version
          - php ./occ maintenance:install --database "sqlite" --admin-user "admin" --admin-pass "admin"
          - php ./occ app:enable $APP_NAME
      tests:
        override:
          - cd ~/build
          - php-scrutinizer-run --enable-security-analysis
          - phpcs-run --standard=.phpcs.xml
          - js-scrutinizer-run

          - cd ~/nextcloud
#          - php ./occ app:check-code $APP_NAME -c private
          - php ./occ app:check-code $APP_NAME -c strong-comparison
          - php ./occ app:check-code $APP_NAME -c deprecation

          - cd ~/nextcloud/apps/$APP_NAME
          - command: php ~/phpunit.phar --configuration tests/phpunit.xml --coverage-clover ~/build/tests/clover.xml
            coverage:
              file: tests/clover.xml
              format: clover

    test-nc14-php70:
      environment:
        php:
          version: 7.0.33
        variables:
          NEXTCLOUD: releases/latest-14
      dependencies:
        override:
          - curl -L -o ~/nextcloud.tar.bz2 https://download.nextcloud.com/server/$NEXTCLOUD.tar.bz2
          - curl -L -o ~/phpunit.phar https://phar.phpunit.de/phpunit-6.phar
      project_setup:
        override:
          - make build
          - cp build/$APP_NAME-*.tar.gz ~/$APP_NAME.tar.gz

          - tar xfjv ~/nextcloud.tar.bz2 -C ~
          - tar xfzv ~/$APP_NAME.tar.gz -C ~/nextcloud/apps
          - cp -rv tests ~/nextcloud/apps/$APP_NAME/tests

          - cd ~/nextcloud
          - php ./occ --version
          - php ./occ maintenance:install --database "sqlite" --admin-user "admin" --admin-pass "admin"
          - php ./occ app:enable $APP_NAME
      tests:
        override:
          - cd ~/nextcloud
#          - php ./occ app:check-code $APP_NAME -c private
          - php ./occ app:check-code $APP_NAME -c strong-comparison
          - php ./occ app:check-code $APP_NAME -c deprecation

          - cd ~/nextcloud/apps/$APP_NAME
          - php ~/phpunit.phar --configuration tests/phpunit.xml

    test-nc14-php71:
      environment:
        php:
          version: 7.1
        variables:
          NEXTCLOUD: releases/latest-14
      dependencies:
        override:
          - curl -L -o ~/nextcloud.tar.bz2 https://download.nextcloud.com/server/$NEXTCLOUD.tar.bz2
          - curl -L -o ~/phpunit.phar https://phar.phpunit.de/phpunit-6.phar
      project_setup:
        override:
          - make build
          - cp build/$APP_NAME-*.tar.gz ~/$APP_NAME.tar.gz

          - tar xfjv ~/nextcloud.tar.bz2 -C ~
          - tar xfzv ~/$APP_NAME.tar.gz -C ~/nextcloud/apps
          - cp -rv tests ~/nextcloud/apps/$APP_NAME/tests

          - cd ~/nextcloud
          - php ./occ --version
          - php ./occ maintenance:install --database "sqlite" --admin-user "admin" --admin-pass "admin"
          - php ./occ app:enable $APP_NAME
      tests:
        override:
          - cd ~/nextcloud
#          - php ./occ app:check-code $APP_NAME -c private
          - php ./occ app:check-code $APP_NAME -c strong-comparison
          - php ./occ app:check-code $APP_NAME -c deprecation

          - cd ~/nextcloud/apps/$APP_NAME
          - php ~/phpunit.phar --configuration tests/phpunit.xml

    test-nc14-php72:
      environment:
        php:
          version: 7.2
        variables:
          NEXTCLOUD: releases/latest-14
      dependencies:
        override:
          - curl -L -o ~/nextcloud.tar.bz2 https://download.nextcloud.com/server/$NEXTCLOUD.tar.bz2
          - curl -L -o ~/phpunit.phar https://phar.phpunit.de/phpunit-6.phar
      project_setup:
        override:
          - make build
          - cp build/$APP_NAME-*.tar.gz ~/$APP_NAME.tar.gz

          - tar xfjv ~/nextcloud.tar.bz2 -C ~
          - tar xfzv ~/$APP_NAME.tar.gz -C ~/nextcloud/apps
          - cp -rv tests ~/nextcloud/apps/$APP_NAME/tests

          - cd ~/nextcloud
          - php ./occ --version
          - php ./occ maintenance:install --database "sqlite" --admin-user "admin" --admin-pass "admin"
          - php ./occ app:enable $APP_NAME
      tests:
        override:
          - cd ~/nextcloud
#          - php ./occ app:check-code $APP_NAME -c private
          - php ./occ app:check-code $APP_NAME -c strong-comparison
          - php ./occ app:check-code $APP_NAME -c deprecation

          - cd ~/nextcloud/apps/$APP_NAME
          - php ~/phpunit.phar --configuration tests/phpunit.xml

    test-nc15-php70:
      environment:
        php:
          version: 7.0.33
        variables:
          NEXTCLOUD: releases/latest-15
      dependencies:
        override:
          - curl -L -o ~/nextcloud.tar.bz2 https://download.nextcloud.com/server/$NEXTCLOUD.tar.bz2
          - curl -L -o ~/phpunit.phar https://phar.phpunit.de/phpunit-6.phar
      project_setup:
        override:
          - make build
          - cp build/$APP_NAME-*.tar.gz ~/$APP_NAME.tar.gz

          - tar xfjv ~/nextcloud.tar.bz2 -C ~
          - tar xfzv ~/$APP_NAME.tar.gz -C ~/nextcloud/apps
          - cp -rv tests ~/nextcloud/apps/$APP_NAME/tests

          - cd ~/nextcloud
          - php ./occ --version
          - php ./occ maintenance:install --database "sqlite" --admin-user "admin" --admin-pass "admin"
          - php ./occ app:enable $APP_NAME
      tests:
        override:
          - cd ~/nextcloud
#          - php ./occ app:check-code $APP_NAME -c private
          - php ./occ app:check-code $APP_NAME -c strong-comparison
          - php ./occ app:check-code $APP_NAME -c deprecation

          - cd ~/nextcloud/apps/$APP_NAME
          - php ~/phpunit.phar --configuration tests/phpunit.xml

    test-nc15-php71:
      environment:
        php:
          version: 7.1
        variables:
          NEXTCLOUD: releases/latest-15
      dependencies:
        override:
          - curl -L -o ~/nextcloud.tar.bz2 https://download.nextcloud.com/server/$NEXTCLOUD.tar.bz2
          - curl -L -o ~/phpunit.phar https://phar.phpunit.de/phpunit-6.phar
      project_setup:
        override:
          - make build
          - cp build/$APP_NAME-*.tar.gz ~/$APP_NAME.tar.gz

          - tar xfjv ~/nextcloud.tar.bz2 -C ~
          - tar xfzv ~/$APP_NAME.tar.gz -C ~/nextcloud/apps
          - cp -rv tests ~/nextcloud/apps/$APP_NAME/tests

          - cd ~/nextcloud
          - php ./occ --version
          - php ./occ maintenance:install --database "sqlite" --admin-user "admin" --admin-pass "admin"
          - php ./occ app:enable $APP_NAME
      tests:
        override:
          - cd ~/nextcloud
#          - php ./occ app:check-code $APP_NAME -c private
          - php ./occ app:check-code $APP_NAME -c strong-comparison
          - php ./occ app:check-code $APP_NAME -c deprecation

          - cd ~/nextcloud/apps/$APP_NAME
          - php ~/phpunit.phar --configuration tests/phpunit.xml

    test-nc15-php72:
      environment:
        php:
          version: 7.2
        variables:
          NEXTCLOUD: releases/latest-15
      dependencies:
        override:
          - curl -L -o ~/nextcloud.tar.bz2 https://download.nextcloud.com/server/$NEXTCLOUD.tar.bz2
          - curl -L -o ~/phpunit.phar https://phar.phpunit.de/phpunit-6.phar
      project_setup:
        override:
          - make build
          - cp build/$APP_NAME-*.tar.gz ~/$APP_NAME.tar.gz

          - tar xfjv ~/nextcloud.tar.bz2 -C ~
          - tar xfzv ~/$APP_NAME.tar.gz -C ~/nextcloud/apps
          - cp -rv tests ~/nextcloud/apps/$APP_NAME/tests

          - cd ~/nextcloud
          - php ./occ --version
          - php ./occ maintenance:install --database "sqlite" --admin-user "admin" --admin-pass "admin"
          - php ./occ app:enable $APP_NAME
      tests:
        override:
          - cd ~/nextcloud
#          - php ./occ app:check-code $APP_NAME -c private
          - php ./occ app:check-code $APP_NAME -c strong-comparison
          - php ./occ app:check-code $APP_NAME -c deprecation

          - cd ~/nextcloud/apps/$APP_NAME
          - php ~/phpunit.phar --configuration tests/phpunit.xml

    test-nc15-php73:
      environment:
        php:
          version: 7.3
        variables:
          NEXTCLOUD: releases/latest-15
      dependencies:
        override:
          - curl -L -o ~/nextcloud.tar.bz2 https://download.nextcloud.com/server/$NEXTCLOUD.tar.bz2
          - curl -L -o ~/phpunit.phar https://phar.phpunit.de/phpunit-6.phar
      project_setup:
        override:
          - make build
          - cp build/$APP_NAME-*.tar.gz ~/$APP_NAME.tar.gz

          - tar xfjv ~/nextcloud.tar.bz2 -C ~
          - tar xfzv ~/$APP_NAME.tar.gz -C ~/nextcloud/apps
          - cp -rv tests ~/nextcloud/apps/$APP_NAME/tests

          - cd ~/nextcloud
          - php ./occ --version
          - php ./occ maintenance:install --database "sqlite" --admin-user "admin" --admin-pass "admin"
          - php ./occ app:enable $APP_NAME
      tests:
        override:
          - cd ~/nextcloud
#          - php ./occ app:check-code $APP_NAME -c private
          - php ./occ app:check-code $APP_NAME -c strong-comparison
          - php ./occ app:check-code $APP_NAME -c deprecation

          - cd ~/nextcloud/apps/$APP_NAME
          - php ~/phpunit.phar --configuration tests/phpunit.xml

    test-nc16-php71:
      environment:
        php:
          version: 7.1
        variables:
          NEXTCLOUD: releases/latest-16
      dependencies:
        override:
          - curl -L -o ~/nextcloud.tar.bz2 https://download.nextcloud.com/server/$NEXTCLOUD.tar.bz2
          - curl -L -o ~/phpunit.phar https://phar.phpunit.de/phpunit-6.phar
      project_setup:
        override:
          - make build
          - cp build/$APP_NAME-*.tar.gz ~/$APP_NAME.tar.gz

          - tar xfjv ~/nextcloud.tar.bz2 -C ~
          - tar xfzv ~/$APP_NAME.tar.gz -C ~/nextcloud/apps
          - cp -rv tests ~/nextcloud/apps/$APP_NAME/tests

          - cd ~/nextcloud
          - php ./occ --version
          - php ./occ maintenance:install --database "sqlite" --admin-user "admin" --admin-pass "admin"
          - php ./occ app:enable $APP_NAME
      tests:
        override:
          - cd ~/nextcloud
#          - php ./occ app:check-code $APP_NAME -c private
          - php ./occ app:check-code $APP_NAME -c strong-comparison
          - php ./occ app:check-code $APP_NAME -c deprecation

          - cd ~/nextcloud/apps/$APP_NAME
          - php ~/phpunit.phar --configuration tests/phpunit.xml

    test-nc16-php72:
      environment:
        php:
          version: 7.2
        variables:
          NEXTCLOUD: releases/latest-16
      dependencies:
        override:
          - curl -L -o ~/nextcloud.tar.bz2 https://download.nextcloud.com/server/$NEXTCLOUD.tar.bz2
          - curl -L -o ~/phpunit.phar https://phar.phpunit.de/phpunit-6.phar
      project_setup:
        override:
          - make build
          - cp build/$APP_NAME-*.tar.gz ~/$APP_NAME.tar.gz

          - tar xfjv ~/nextcloud.tar.bz2 -C ~
          - tar xfzv ~/$APP_NAME.tar.gz -C ~/nextcloud/apps
          - cp -rv tests ~/nextcloud/apps/$APP_NAME/tests

          - cd ~/nextcloud
          - php ./occ --version
          - php ./occ maintenance:install --database "sqlite" --admin-user "admin" --admin-pass "admin"
          - php ./occ app:enable $APP_NAME
      tests:
        override:
          - cd ~/nextcloud
#          - php ./occ app:check-code $APP_NAME -c private
          - php ./occ app:check-code $APP_NAME -c strong-comparison
          - php ./occ app:check-code $APP_NAME -c deprecation

          - cd ~/nextcloud/apps/$APP_NAME
          - php ~/phpunit.phar --configuration tests/phpunit.xml

    test-nc16-php73:
      environment:
        php:
          version: 7.3
        variables:
          NEXTCLOUD: releases/latest-16
      dependencies:
        override:
          - curl -L -o ~/nextcloud.tar.bz2 https://download.nextcloud.com/server/$NEXTCLOUD.tar.bz2
          - curl -L -o ~/phpunit.phar https://phar.phpunit.de/phpunit-6.phar
      project_setup:
        override:
          - make build
          - cp build/$APP_NAME-*.tar.gz ~/$APP_NAME.tar.gz

          - tar xfjv ~/nextcloud.tar.bz2 -C ~
          - tar xfzv ~/$APP_NAME.tar.gz -C ~/nextcloud/apps
          - cp -rv tests ~/nextcloud/apps/$APP_NAME/tests

          - cd ~/nextcloud
          - php ./occ --version
          - php ./occ maintenance:install --database "sqlite" --admin-user "admin" --admin-pass "admin"
          - php ./occ app:enable $APP_NAME
      tests:
        override:
          - cd ~/nextcloud
#          - php ./occ app:check-code $APP_NAME -c private
          - php ./occ app:check-code $APP_NAME -c strong-comparison
          - php ./occ app:check-code $APP_NAME -c deprecation

          - cd ~/nextcloud/apps/$APP_NAME
          - php ~/phpunit.phar --configuration tests/phpunit.xml

    test-master-php71:
      environment:
        php:
          version: 7.1
        variables:
          NEXTCLOUD: daily/latest-master
      dependencies:
        override:
          - curl -L -o ~/nextcloud.tar.bz2 https://download.nextcloud.com/server/$NEXTCLOUD.tar.bz2
          - curl -L -o ~/phpunit.phar https://phar.phpunit.de/phpunit-6.phar
      project_setup:
        override:
          - make build
          - cp build/$APP_NAME-*.tar.gz ~/$APP_NAME.tar.gz

          - tar xfjv ~/nextcloud.tar.bz2 -C ~
          - tar xfzv ~/$APP_NAME.tar.gz -C ~/nextcloud/apps
          - cp -rv tests ~/nextcloud/apps/$APP_NAME/tests

          - cd ~/nextcloud
          - php ./occ --version
          - php ./occ maintenance:install --database "sqlite" --admin-user "admin" --admin-pass "admin"
          - php ./occ app:enable $APP_NAME
      tests:
        override:
          - cd ~/nextcloud
#          - php ./occ app:check-code $APP_NAME -c private
          - php ./occ app:check-code $APP_NAME -c strong-comparison
          - php ./occ app:check-code $APP_NAME -c deprecation

          - cd ~/nextcloud/apps/$APP_NAME
          - php ~/phpunit.phar --configuration tests/phpunit.xml

    test-master-php72:
      environment:
        php:
          version: 7.2
        variables:
          NEXTCLOUD: daily/latest-master
      dependencies:
        override:
          - curl -L -o ~/nextcloud.tar.bz2 https://download.nextcloud.com/server/$NEXTCLOUD.tar.bz2
          - curl -L -o ~/phpunit.phar https://phar.phpunit.de/phpunit-6.phar
      project_setup:
        override:
          - make build
          - cp build/$APP_NAME-*.tar.gz ~/$APP_NAME.tar.gz

          - tar xfjv ~/nextcloud.tar.bz2 -C ~
          - tar xfzv ~/$APP_NAME.tar.gz -C ~/nextcloud/apps
          - cp -rv tests ~/nextcloud/apps/$APP_NAME/tests

          - cd ~/nextcloud
          - php ./occ --version
          - php ./occ maintenance:install --database "sqlite" --admin-user "admin" --admin-pass "admin"
          - php ./occ app:enable $APP_NAME
      tests:
        override:
          - cd ~/nextcloud
#          - php ./occ app:check-code $APP_NAME -c private
          - php ./occ app:check-code $APP_NAME -c strong-comparison
          - php ./occ app:check-code $APP_NAME -c deprecation

          - cd ~/nextcloud/apps/$APP_NAME
          - php ~/phpunit.phar --configuration tests/phpunit.xml

    test-master-php73:
      environment:
        php:
          version: 7.3
        variables:
          NEXTCLOUD: daily/latest-master
      dependencies:
        override:
          - curl -L -o ~/nextcloud.tar.bz2 https://download.nextcloud.com/server/$NEXTCLOUD.tar.bz2
          - curl -L -o ~/phpunit.phar https://phar.phpunit.de/phpunit-6.phar
      project_setup:
        override:
          - make build
          - cp build/$APP_NAME-*.tar.gz ~/$APP_NAME.tar.gz

          - tar xfjv ~/nextcloud.tar.bz2 -C ~
          - tar xfzv ~/$APP_NAME.tar.gz -C ~/nextcloud/apps
          - cp -rv tests ~/nextcloud/apps/$APP_NAME/tests

          - cd ~/nextcloud
          - php ./occ --version
          - php ./occ maintenance:install --database "sqlite" --admin-user "admin" --admin-pass "admin"
          - php ./occ app:enable $APP_NAME
      tests:
        override:
          - cd ~/nextcloud
#          - php ./occ app:check-code $APP_NAME -c private
          - php ./occ app:check-code $APP_NAME -c strong-comparison
          - php ./occ app:check-code $APP_NAME -c deprecation

          - cd ~/nextcloud/apps/$APP_NAME
          - php ~/phpunit.phar --configuration tests/phpunit.xml

checks:
  php: true
  javascript: true

filter:
  excluded_paths:
    - appdata/plugins/
    - appdata/themes/
    - build/
    - l10n/
    - tests/
  dependency_paths:
    - vendor/
    - nextcloud/
